apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20231022040636.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20231022040636.0.0+build.02e9424
  releaseNotes: |
    Release v20231022040636.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-21-10-2023-23-52-30-163774130/where-for-dinner-search-my-apps-bundle@sha256:6428b0f8e3f3dd75d2a64f553e776719a092fdd80073800a85c0acd8d4c4e4e7
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

