apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20231022040616.0.0+build.02e9424
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20231022040616.0.0+build.02e9424
  releaseNotes: |
    Release v20231022040616.0.0+build.02e9424 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-21-10-2023-23-52-30-163774130/where-for-dinner-ui-my-apps-bundle@sha256:f76fe949e6a7a2e9349e21d023211ab8570523a177dbcaece8a77371d13db730
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

