apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231022040541.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231022040541.0.0+build.02e9424
  releaseNotes: |
    Release v20231022040541.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-21-10-2023-23-52-30-163774130/where-for-dinner-my-apps-bundle@sha256:20c511880fd7e5ab3cbcae1f708213309655f27fdac468417a38e91203d8101b
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

